- README.md
- tournament-scheduler/package-lock.json
- tournament-scheduler/package.json
- tournament-scheduler/src/App.css
- tournament-scheduler/src/App.tsx
- tournament-scheduler/src/LoginForm/LoginForm.css
- tournament-scheduler/src/LoginForm/LoginForm.tsx
- tournament-scheduler/src/LoginForm/SrcApiKeyLink.tsx
- tournament-scheduler/src/ScheduleManagement/ScheduleManagement.tsx
> Tournament scheduler/mobile fixes

- assets/js/scoreboard-datatable.js
- flask_app.py
- models.py
- user_updater.py
> Allow users to login despite not being in the leaderboard

- flask_app.py
- user_updater.py
Try again with pooling SQL connections for cache
> Set a cap to points

- tournament-scheduler/src/ScheduleRegistration/ScheduleRegistration.tsx
- tournament-scheduler/src/ScheduleViewer/ScheduleViewer.tsx
- tournament-scheduler/src/index.css
closes #38 
closes #27 
closes #39
> Tournament scheduler/post qualifications update

- assets/js/scoreboard-datatable.js
- flask_app.py
- models.py
- tournament-scheduler/src/ScheduleRegistration/ScheduleRegistration.tsx
- tournament-scheduler/src/ScheduleViewer/ScheduleViewer.tsx
- tournament-scheduler/src/index.css
> Cache requests probable final fix

- global_scoreboard/.eslintrc.json
- global_scoreboard/package-lock.json
- global_scoreboard/package.json
- global_scoreboard/src/fetchers/api.ts
- tournament-scheduler/.eslintrc.json
- tournament-scheduler/package-lock.json
- tournament-scheduler/package.json
- tournament-scheduler/src/ScheduleManagement/ScheduleManagement.tsx
- tournament-scheduler/src/ScheduleManagement/ScheduleWizard.tsx
- tournament-scheduler/src/ScheduleRegistration/ScheduleRegistration.tsx
- tournament-scheduler/src/ScheduleViewer/ScheduleViewer.tsx
- tournament-scheduler/src/fetchers/api.ts
> Tournament scheduler/#28 extract ajax calls to their own services

- assets/js/scoreboard-datatable.js
- global-scoreboard/package.json
- global-scoreboard/public/index.html
- global-scoreboard/src/Dashboard/Dashboard.tsx
- utils.py
> Retry delay spreading from 5 to 15s. Small metadata adjustments

- tournament-scheduler/src/ScheduleRegistration/ScheduleRegistration.tsx
- tournament-scheduler/src/ScheduleViewer/ScheduleViewer.tsx
> Improved some user messages

- tournament-scheduler/src/ScheduleViewer/ScheduleViewer.tsx
> Don't split participants per entry if maximum of 1 participant per entry

- Changescripts/2020-04-10-Added-country-code.sql
- api.py
- global-scoreboard/src/Dashboard/Dashboard.css
- global-scoreboard/src/Dashboard/Dashboard.tsx
- global-scoreboard/src/Dashboard/QuickView.tsx
- global-scoreboard/src/Dashboard/Scoreboard.tsx
- global-scoreboard/src/models/Player.ts
- global-scoreboard/src/models/UpdateRunnerResult.ts
- models.py
- user_updater.py
> Added regional flags by users' name

- global-scoreboard/src/Dashboard/Dashboard.css
- global-scoreboard/src/Dashboard/Dashboard.tsx
- global-scoreboard/src/models/UpdateRunnerResult.ts
- templates/index.html
- user_updater.py
> Ignore multi game and fix 504 response crash

- global-scoreboard/src/Dashboard/Dashboard.css
- global-scoreboard/src/Dashboard/Dashboard.tsx
- global-scoreboard/src/Dashboard/QuickView.css
- global-scoreboard/src/Dashboard/QuickView.tsx
- global-scoreboard/src/Dashboard/Scoreboard.tsx
- models.py
> Reimplement loading bar in react version

- api.py
- assets/css/custom.css
- assets/js/scoreboard-datatable.js
- configs.template.py
- global-scoreboard/src/App.tsx
- global-scoreboard/src/Dashboard/Dashboard.css
- global-scoreboard/src/Dashboard/Scoreboard.tsx
- global-scoreboard/src/models/Configs.ts
- global-scoreboard/src/react-bootstrap-table-next.d.ts
- models.py
- user_updater.py
> Update last updating timings

- global-scoreboard/src/Dashboard/Scoreboard.css
- global-scoreboard/src/Dashboard/Scoreboard.tsx
- global-scoreboard/src/react-bootstrap-table-next.d.ts
> Added column sort

- global-scoreboard/src/App.tsx
- global-scoreboard/src/Dashboard/Dashboard.tsx
- global-scoreboard/src/Dashboard/Scoreboard.tsx
- global-scoreboard/src/index.tsx
- tournament-scheduler/src/LoginForm/LoginForm.tsx
> Infer rank from existing board

- global-scoreboard/src/Dashboard/Scoreboard.tsx
- global-scoreboard/src/react-bootstrap-table-next.d.ts
> Reset the search upon Jumping to player #106

- api.py
- assets/js/scoreboard-datatable.js
- global-scoreboard/src/Dashboard/Dashboard.tsx
- user_updater.py
> Update user update warnings

- global-scoreboard/src/Dashboard/Dashboard.tsx
- global-scoreboard/src/Dashboard/Scoreboard.tsx
- global-scoreboard/src/models/Player.ts
- models.py
Fixes #105, fixes #109
Also Optimized buildSortFunction and made infered rank more accurate
> Fixing jump to player with different sort

- api/global_scoreboard_api.py
- global-scoreboard/src/Dashboard/Dashboard.tsx
- models/core_models.py
> Quickview score details doesnt update #123

- models/global_scoreboard_models.py
> Some users with too many runs are impossible to update #111

- global-scoreboard/src/Dashboard/Dashboard.tsx
> fix "mintues" typo

- global-scoreboard/src/Components/App.tsx
- tournament-scheduler/package-lock.json
- tournament-scheduler/package.json
- tournament-scheduler/patches/@culturehq+add-to-calendar+1.1.2.patch
- tournament-scheduler/src/Components/App.tsx
- tournament-scheduler/src/Components/ScheduleManagement/ScheduleWizard/ScheduleWizard.tsx
- tournament-scheduler/src/Components/ScheduleViewer/ScheduleGroupViewer.tsx
- tournament-scheduler/src/index.tsx
Also raised an issue: https://github.com/CultureHQ/add-to-calendar/issues/601
> Fixed #250 for real this time
